version: "3.5"

services:
  ffmpegServer:
    image: necromant/ffmpeg-server
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    configs:
      - source: ffmpeg_server
        target: /etc/ffmpeg-server/config
        mode: 0444
    volumes:
      - /var/lib/ffmpeg-server/upload:/var/lib/ffmpeg-server/upload
      - /media/hidrive/users/xhq6savpdkk9cruusg9a4najh/movies/:/var/lib/ffmpeg-server/conversion

networks:
  public:
    external: true

configs:
  ffmpeg_server:
    file: ./config.yaml